name: ramadan_kareem
description: ramadan kareem
publish_to: 'none'
version: 2023.1.3+14

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hijri: ^3.0.0
  flutter_svg: ^2.0.3
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  sizer: ^2.0.15
  platform_device_id: ^1.0.1
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  adhan: ^2.0.0-nullsafety.2
  geocode: ^1.0.1
  geolocator: ^9.0.2
  share_plus: ^6.3.0
#  firebase
  firebase_core: ^2.8.0
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.4.5
  firebase_messaging: ^14.3.0
  provider: ^6.0.5

  salomon_bottom_bar: ^3.1.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  # routes handler
  fluro: ^2.0.4
  shimmer: ^2.0.0
  connectivity_plus: ^2.3.7
  internet_connection_checker: ^0.0.1+4
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.7
  inview_notifier_list: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/images/
    - assets/data/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 600
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 700

    - family: Lalezar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf

  uses-material-design: true


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
